CREATE TABLE agents (
  id INT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1),
  name VARCHAR(32) NOT NULL,
  address VARCHAR(255) NOT NULL,
  login VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE estates (
  id INT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1),
  city VARCHAR(255) NOT NULL,
  zip INT NOT NULL,
  street VARCHAR(255) NOT NULL,
  number INT NOT NULL,
  area VARCHAR(255) NOT NULL,
  agent INT NOT NULL,
  CONSTRAINT fk_agent FOREIGN KEY (agent) REFERENCES AGENTS (ID)
);

CREATE TABLE apartments (
  id INT PRIMARY KEY NOT NULL,
  floor INT NOT NULL,
  rent SMALLINT DEFAULT 0 NOT NULL,
  rooms DOUBLE NOT NULL,
  kitchen SMALLINT DEFAULT 0 NOT NULL,
  balcony SMALLINT DEFAULT 0 NOT NULL,
  CONSTRAINT Apartments_ESTATE_ID_fk FOREIGN KEY (id) REFERENCES ESTATES (ID)
);

CREATE TABLE contracts
(
    id INT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1),
    deal DATE NOT NULL,
    place VARCHAR(255) NOT NULL
);

CREATE TABLE purchases
(
    id INT PRIMARY KEY NOT NULL,
    installments INT NOT NULL,
    rate INT NOT NULL,
    CONSTRAINT fk_contracts FOREIGN KEY (id) REFERENCES CONTRACTS (ID)
);

CREATE TABLE tenancies
(
    id INT PRIMARY KEY NOT NULL,
    start DATE NOT NULL,
    duration INT NOT NULL,
    cost INT NOT NULL,
    CONSTRAINT fk_contract FOREIGN KEY (id) REFERENCES CONTRACTS (ID)
);

CREATE TABLE houses
(
    id INT PRIMARY KEY NOT NULL,
    floors INT NOT NULL,
    price DOUBLE NOT NULL,
    garden SMALLINT NOT NULL,
    CONSTRAINT fk_estate FOREIGN KEY (id) REFERENCES ESTATES (ID)
);

CREATE TABLE persons
(
    id INT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1),
    firstname VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL
);
CREATE TABLE sells
(
    id INT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1),
    person INT NOT NULL,
    purchase INT NOT NULL,
    house INT NOT NULL,
    CONSTRAINT fk_person FOREIGN KEY (person) REFERENCES PERSONS (ID),
    CONSTRAINT fk_house FOREIGN KEY (house) REFERENCES HOUSES (ID),
    CONSTRAINT fk_purchase FOREIGN KEY (purchase) REFERENCES PURCHASES (ID)
);

CREATE TABLE rents
(
    id INT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1),
    apartment INT,
    tenancy INT NOT NULL,
    person INT,
    CONSTRAINT fk_apartment FOREIGN KEY (apartment) REFERENCES APARTMENTS (ID),
    CONSTRAINT fk_tenancies FOREIGN KEY (tenancy) REFERENCES TENANCIES (ID),
    CONSTRAINT fk_person FOREIGN KEY (person) REFERENCES PERSONS (ID)
);
